# Generated by Django 4.1.1 on 2022-11-18 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fatec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatec', models.CharField(max_length=100, unique=True)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('endereco', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('site', models.CharField(blank=True, max_length=100)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('linkedin', models.CharField(blank=True, max_length=100)),
                ('data_inauguracao', models.DateField(null=True, verbose_name='Data de Inauguração')),
                ('criado_em', models.DateTimeField(auto_now=True, verbose_name='criado em')),
                ('ativa', models.BooleanField(default=True, verbose_name='ativa')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('regiao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.regiao', verbose_name='região')),
            ],
            options={
                'verbose_name': 'Fatec',
                'verbose_name_plural': 'Fatecs',
                'ordering': ('fatec',),
            },
        ),
    ]
