# Generated by Django 4.1.1 on 2022-11-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatec',
            name='institucional',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fatec',
            name='data_inauguracao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Inauguração'),
        ),
    ]
