# Generated by Django 4.1.1 on 2022-11-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fatec_institucional_alter_fatec_data_inauguracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatec',
            name='telefone',
            field=models.CharField(blank=True, max_length=100, verbose_name='telefone'),
        ),
    ]
