# Generated by Django 4.1.1 on 2022-11-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_fatec_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatec',
            name='youtube',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
