# Generated by Django 4.1.1 on 2022-11-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fatec_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatec',
            name='googlemaps',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='fatec',
            name='facebook',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fatec',
            name='instagram',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fatec',
            name='linkedin',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fatec',
            name='site',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='fatec',
            name='youtube',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
