# Generated by Django 4.1.1 on 2022-11-18 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_fatec_facebook_alter_fatec_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='fatecs')),
                ('fatec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fatec')),
            ],
            options={
                'verbose_name': 'imagem',
                'verbose_name_plural': 'imagens',
                'ordering': ('-fatec',),
            },
        ),
    ]
