# Generated by Django 4.1.1 on 2022-11-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_imagem_options_remove_imagem_fatec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatec',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='fatecs', verbose_name='Fachada'),
        ),
        migrations.DeleteModel(
            name='Imagem',
        ),
    ]
