# Generated by Django 4.1.1 on 2022-11-18 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatec',
            name='email',
        ),
        migrations.RemoveField(
            model_name='fatec',
            name='telefone',
        ),
    ]
