# Generated by Django 4.1.1 on 2022-11-18 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_fatec_email_remove_fatec_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='kind',
            field=models.CharField(choices=[('E', 'Email'), ('P', 'Telefone'), ('W', 'Whatsapp')], max_length=1, verbose_name='tipo'),
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('W', 'Site'), ('F', 'Facebook'), ('I', 'Instagram')], max_length=1, verbose_name='tipo')),
                ('value', models.CharField(max_length=255, verbose_name='valor')),
                ('Fatec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fatec', verbose_name='Fatec')),
            ],
            options={
                'verbose_name': 'endereço social',
                'verbose_name_plural': 'enderecos sociais',
            },
        ),
    ]
