# Generated by Django 4.1.1 on 2022-11-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_contact_kind_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatec',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='fatec',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='fatec',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='fatec',
            name='youtube',
        ),
        migrations.AlterField(
            model_name='social',
            name='kind',
            field=models.CharField(choices=[('W', 'Site'), ('F', 'Facebook'), ('I', 'Instagram'), ('Y', 'Youtube'), ('L', 'Linkedin'), ('T', 'Twitter'), ('B', 'Blog'), ('O', 'Outros')], max_length=1, verbose_name='tipo'),
        ),
    ]
