# Generated by Django 4.1.1 on 2022-11-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_fatec_facebook_remove_fatec_instagram_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ('curso',), 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AddField(
            model_name='curso',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='ativa'),
        ),
        migrations.AddField(
            model_name='curso',
            name='conteudo_estudo',
            field=models.TextField(blank=True, null=True, verbose_name='O aluno estuda'),
        ),
        migrations.AddField(
            model_name='curso',
            name='curso',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='curso',
            name='eixo_tecnologico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='mercado_trabalho',
            field=models.TextField(blank=True, null=True, verbose_name='Mercado de trabalho'),
        ),
        migrations.AddField(
            model_name='curso',
            name='profissional_faz',
            field=models.TextField(blank=True, null=True, verbose_name='O profisisonal faz'),
        ),
        migrations.AddField(
            model_name='curso',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fatec',
            name='cursos',
            field=models.ManyToManyField(blank=True, null=True, to='core.curso'),
        ),
    ]
