# Generated by Django 4.1.1 on 2022-11-18 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_curso_options_curso_ativa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EixoTecnologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eixo_tecnologico', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='curso',
            name='eixo_tecnologico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.eixotecnologico'),
        ),
    ]
