# Generated by Django 4.1.1 on 2022-11-18 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_eixo_tecnologico_curso_eixo_tecnologico2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='eixo_tecnologico2',
            new_name='eixo_tecnologico',
        ),
    ]
