# Generated by Django 4.1.1 on 2022-11-18 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_eixo_tecnologico2_curso_eixo_tecnologico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='eixo_tecnologico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.eixotecnologico'),
        ),
    ]
