# Generated by Django 4.1.1 on 2022-11-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_curso_eixo_tecnologico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatec',
            name='cursos',
            field=models.ManyToManyField(blank=True, to='core.curso'),
        ),
    ]
