# Generated by Django 4.1.1 on 2022-11-18 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_fatec_cursos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='ativa',
            new_name='ativo',
        ),
        migrations.RenameField(
            model_name='fatec',
            old_name='ativa',
            new_name='ativo',
        ),
    ]
