# Generated by Django 4.1.1 on 2022-11-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_curso_materia_1_curso_materia_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoVestibularFatec',
            fields=[
                ('cod_resultado_fatec', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('cod_curso', models.IntegerField()),
                ('cod_instituicao', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('periodo', models.CharField(max_length=10)),
                ('qtde_vagas', models.IntegerField()),
                ('qtde_inscrito', models.IntegerField()),
                ('demanda', models.FloatField()),
                ('nota_corte', models.FloatField()),
                ('nota_maxima', models.FloatField()),
            ],
            options={
                'verbose_name': 'resultado do vestibular da fatec',
                'verbose_name_plural': 'resultados do vestibulares da fatec',
            },
        ),
    ]
