# Generated by Django 4.1.1 on 2022-11-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_resultadovestibularfatec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='materia_1',
            field=models.CharField(blank=True, choices=[('BIO', 'BIOLOGIA'), ('CONG', 'CONHECIMENTO GERAIS'), ('FIS', 'FÍSICA'), ('GEO', 'GEOGRAFIA'), ('HIST', 'HISTÓRIA'), ('ING', 'INGLÊS'), ('MAT', 'MATEMÁTICA'), ('PORT', 'PORTUGUÊS'), ('RLOG', 'RACIOCÍNIO LÓGICO'), ('QUI', 'QUÍMICA')], max_length=4, verbose_name='Materia peso 2 (1ª)'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='materia_2',
            field=models.CharField(blank=True, choices=[('BIO', 'BIOLOGIA'), ('CONG', 'CONHECIMENTO GERAIS'), ('FIS', 'FÍSICA'), ('GEO', 'GEOGRAFIA'), ('HIST', 'HISTÓRIA'), ('ING', 'INGLÊS'), ('MAT', 'MATEMÁTICA'), ('PORT', 'PORTUGUÊS'), ('RLOG', 'RACIOCÍNIO LÓGICO'), ('QUI', 'QUÍMICA')], max_length=4, verbose_name='Materia peso 2 (2ª)'),
        ),
    ]
