# Generated by Django 4.1.1 on 2022-11-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_curso_materia_1_alter_curso_materia_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatec',
            name='googlemaps_iframe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
