# Generated by Django 4.1.3 on 2022-12-01 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_fatec_googlemaps_iframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadovestibularfatec',
            name='cod_curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.curso'),
        ),
    ]
