# Generated by Django 4.1.3 on 2022-12-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_fatec_googlemaps_iframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadovestibularfatec',
            name='cod_curso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadovestibularfatec',
            name='cod_instituicao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
