# Generated by Django 4.1.3 on 2022-12-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_resultadovestibularfatec_cod_instituicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadovestibularfatec',
            name='cod_curso',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='resultadovestibularfatec',
            name='cod_instituicao',
            field=models.IntegerField(),
        ),
    ]
