# Generated by Django 4.1.3 on 2022-12-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_resultadovestibularfatec2'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='destaque',
            field=models.TextField(blank=True, null=True, verbose_name='Destaque'),
        ),
        migrations.AddField(
            model_name='curso',
            name='sugestao_cursos',
            field=models.TextField(blank=True, null=True, verbose_name='Sugestões de cursos'),
        ),
        migrations.AddField(
            model_name='curso',
            name='visao_geral',
            field=models.TextField(blank=True, null=True, verbose_name='Visão geral'),
        ),
    ]
