# Generated by Django 4.1.3 on 2023-04-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_disciplinas_alter_curso_materia_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplinas',
            options={'ordering': ('disciplina',), 'verbose_name': 'Diciplina da prova', 'verbose_name_plural': 'Disciplinas da prova'},
        ),
        migrations.AlterField(
            model_name='disciplinas',
            name='quantidade_questoes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Quantidade de questões'),
        ),
    ]
