# Generated by Django 4.1.3 on 2022-12-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoSeletivoVestibularFatec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField(blank=True, null=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('edicao', models.CharField(blank=True, max_length=20, null=True, verbose_name='edição')),
                ('formato_processo', models.CharField(choices=[('AN', 'Análise Histórico Escolar'), ('EX', 'Exame')], default='EX', max_length=2, verbose_name='formato de seleção')),
                ('edital', models.FileField(blank=True, null=True, upload_to='provas')),
                ('data_prova', models.DateField(blank=True, null=True, verbose_name='data do exame')),
                ('link_prova', models.URLField(blank=True, max_length=500, null=True)),
                ('prova', models.FileField(blank=True, null=True, upload_to='provas')),
                ('gabarito', models.FileField(blank=True, null=True, upload_to='provas')),
                ('total_vagas', models.IntegerField(blank=True, null=True, verbose_name='total de vagas')),
                ('total_inscritos', models.IntegerField(blank=True, null=True, verbose_name='total de inscritos')),
                ('qtde_questoes_anulada', models.IntegerField(blank=True, null=True, verbose_name='quantidade de questões anuladas')),
                ('qtde_fatecs', models.IntegerField(blank=True, null=True, verbose_name='quantidade de fatecs no processo seletivo')),
                ('qtde_cursos', models.IntegerField(blank=True, null=True, verbose_name='quantidade de cursos no processo seletivo')),
                ('simulado_gratuito', models.BooleanField(default=False, verbose_name='simulado gratuito')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='observação')),
                ('criado_em', models.DateTimeField(auto_now=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'processo seletivo do vestibular da fatec',
                'verbose_name_plural': 'processos seletivos dos vestibulares da fatec',
                'ordering': ('-semestre', '-ano'),
            },
        ),
    ]
