# Generated by Django 5.2.8 on 2025-11-23 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_disciplinas_options_and_more'),
        ('simulados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('enunciado', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='questoes')),
                ('anulada', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.disciplinas')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='simulados.processoseletivovestibularfatec')),
            ],
            options={
                'ordering': ('numero',),
                'unique_together': {('processo', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(blank=True, max_length=2, null=True)),
                ('texto', models.TextField()),
                ('correta', models.BooleanField(default=False)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='simulados.questao')),
            ],
        ),
        migrations.CreateModel(
            name='SimuladoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('total_questoes', models.IntegerField(blank=True, null=True)),
                ('nota_maxima', models.FloatField(blank=True, null=True)),
                ('tempo_limite_minutos', models.IntegerField(blank=True, null=True)),
                ('publico', models.BooleanField(default=False)),
                ('questoes', models.ManyToManyField(blank=True, related_name='simulados_personalizados', to='simulados.questao')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TentativaSimulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('tempo_segundos', models.IntegerField(blank=True, null=True)),
                ('nota_final', models.FloatField(blank=True, null=True)),
                ('simulado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas', to='simulados.simuladopersonalizado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RespostaDoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correta', models.BooleanField(default=False)),
                ('marcado_em', models.DateTimeField(auto_now_add=True)),
                ('alternativa_marcada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulados.alternativa')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulados.questao')),
                ('tentativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='simulados.tentativasimulado')),
            ],
            options={
                'unique_together': {('tentativa', 'questao')},
            },
        ),
    ]
